### ISSUE TITLE
Todo : Windows : Dépos et exécution du script

### ISSUE THREAD

**Issue by balllou** [balllou/STEG_rubber_ducky#4]
Pour exécuter la payload côté Windows, il faudra la déposer sur la machine ou avoir un reverse shell. 
Il faut donc trouver un moyen d'écrire un script sur la machine ou de déposer le notre et l'exécuter.

- [ ] Dépos d'un fichier depuis arduino vers la machine windows
- [ ] écriture d'un fichier par arduino sur la machine windows via reverse shell
- [x] Exécution directe via reverse shell

**Comment by SarahCary** [comment]
Telecharger Arduino: https://www.arduino.cc/en/Main/Software
Telecharger extension teensy: https://www.pjrc.com/teensy/td_download.html

**Comment by balllou** [comment]
pour l'instant exécution directe via reverse shell -> à voir si pertinent de déposer/écrire un script sur la machine

**Comment by balllou** [comment]
Todo : penser à supprimer les éventuels fichiers intermédiaires qui seront créés
