### ISSUE TITLE
Todo : Linux : transmission des données

### ISSUE THREAD

**Issue by balllou** [balllou/STEG_rubber_ducky#7]
Réaliser un script qui lis un fichier texte ou CSV, le convertit en chaîne binaire et pilote la luminosité de l'écran en fonction de la valeur de chaque bit de la chaîne : si 1 -> luminosité max, si 0 -> minimum.

- [x] lecture du fichier
- [x] conversion en chaîne binaire
- [x] changement de la luminosité.

**Comment by balllou** [comment]
tâches complétées -> clôture
[file_to_light.zip](https://github.com/balllou/STEG_rubber_ducky/files/4695016/file_to_light.zip)
